[versions]
clikt = "5.0.3"
gson = "2.11.0"
guava = "33.3.1-jre"

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.20" }

[libraries]
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version.ref = "clikt" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
